Update update-stats.yml

diff --git a/.github/workflows/update-stats.yml b/.github/workflows/update-stats.yml
--- a/.github/workflows/update-stats.yml
+++ b/.github/workflows/update-stats.yml
@@ -1,43 +1,36 @@
-name: Cache Action
+name: Update README
+
 on:
-  workflow_dispatch:
   schedule:
-    - cron: 0 */4 * * * # Every 4 hours, change it accordingly
+    - cron: '0 0 * * *' # Ejecuta diariamente a medianoche UTC
+  workflow_dispatch: # Permite ejecutar la acción manualmente
 
 jobs:
-  stats:
-    permissions: write-all
+  build:
     runs-on: ubuntu-latest
-    name: Stats Card
-    steps:
-      - uses: actions/checkout@v3
-        name: Check out current commit
-      - uses: suisei-cn/actions-download-file@v1.3.0
-        id: stats
-        name: Download the stats file
-        with:
-          url: "https://github-readme-stats.vercel.app/api?username=username" # Put your own vercel instance URL here
-          target: grs
-          filename: stats.svg # Need to have the file name prepared as svg
-      - uses: actions/upload-artifact@master
-        with:
-          name: stats
-          path: grs
 
-  push:
-    permissions: write-all
-    runs-on: ubuntu-latest
-    name: Push
-    needs: [stats] # Put any jobs (card) needed here before we push
     steps:
-      - uses: actions/download-artifact@master
-        with:
-          name: stats
-          path: grs
-      - name: Push
-        uses: crazy-max/ghaction-github-pages@v3
-        with:
-          target_branch: resource/grs # May change to your desired branch name, the final URL need to be updated if you change this
-          build_dir: grs
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    - name: Checkout repository content
+      uses: actions/checkout@v3
+
+    - name: Setup Node.js
+      uses: actions/setup-node@v3
+      with:
+        node-version: '16'
+
+    - name: Generate language stats
+      run: |
+        npx @lowlighter/metrics@latest
+        ls -la  # Lista los archivos generados para ver qué se ha creado
+        cat README.md  # Muestra el contenido del README.md para verificar los cambios
+
+    - name: Configure Git
+      run: |
+        git config --global user.name 'GitHub Actions'
+        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
+
+    - name: Commit and push changes
+      run: |
+        git add README.md
+        git commit -m "Update language stats in profile" || echo "No changes to commit"
+        git push || echo "Failed to push changes"
